# ===================================================
# --- Configuração Geral da Aplicação ---
# ===================================================
# Nome da sua aplicação Spring
spring.application.name=femmcode

# Porta em que o servidor backend irá rodar
server.port=8080


# ===================================================
# --- Configuração do Banco de Dados MongoDB ---
# ===================================================
# A URI de conexão já inclui o host, porta e nome do banco de dados.
# As outras linhas (host, port, database) são redundantes quando a URI é usada.
spring.data.mongodb.uri=mongodb://localhost:27017/femmcode
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO





# ===================================================
# --- Configuração do JSON Web Token (JWT) ---
# ===================================================
# Adicionadas para corrigir o erro de inicialização.
#
# Chave secreta usada para assinar e validar os tokens.
# Em um ambiente de produção, esta chave deve ser muito mais complexa e segura.
app.jwt.secret=ZmVtbWNvZGUtYXBwbGljYXRpb24tYW5kLXRoaXMtaXMtYS12ZXJ5LWxvbmctYW5kLXNlY3VyZS1rZXktZm9yLUhTNTEy

# Tempo de expiração do token em milissegundoss.
# 86400000 = 24 horas
app.jwt.expiration-ms=86400000


# ===================================================
# --- Configuração de E-mail (para 'Esqueci a Senha') ---
# ===================================================
# Descomente e preencha estas linhas quando formos implementar o envio de e-mail.
 spring.mail.host=smtp.gmail.com
 spring.mail.port=587
 spring.mail.username=femmcode4@gmail.com
 spring.mail.password=bois jera nrdp tayz
 spring.mail.properties.mail.smtp.auth=true
 spring.mail.properties.mail.smtp.starttls.enable=true


spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=file:uploads/

cloudinary.cloud_name=dfykqixct
cloudinary.api_key=982797947962238
cloudinary.api_secret=Yz9o2Md73F450i5LXO-X2cvlNe0

app.frontend.url=http://localhost:5173

upload.path=C:/Users/Kauane/Desktop/StemGirls/uploads












