spring.application.name=femmcode

server.port=8080

spring.data.mongodb.uri=mongodb://mongodb:27017/femmcode
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO

app.jwt.secret=ZmVtbWNvZGUtYXBwbGljYXRpb24tYW5kLXRoaXMtaXMtYS12ZXJ5LWxvbmctYW5kLXNlY3VyZS1rZXktZm9yLUhTNTEy

app.jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=femmcode4@gmail.com
spring.mail.password=bois jera nrdp tayz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=file:uploads/

cloudinary.cloud_name=dfykqixct
cloudinary.api_key=982797947962238
cloudinary.api_secret=Yz9o2Md73F450i5LXO-X2cvlNe0

app.frontend.url=http://localhost:8000

upload.path=C:/Users/Kauane/Desktop/StemGirls/uploads












